---
# file: roles/openaz-quiesce/tasks/main.yml

- name: Stop Manifold services.
  systemd:
    name: manifold-runsvdir.service
    state: stopped

- name: Unmount Manifold NAS shares.
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: nfs
    opts: "{{ qnas_nfs_opts }}"
    state: unmounted
  loop:
    - { src: "qnas1.library.arizona.edu:/{{vm_hostname}}-manifold-var", path: "/var/opt/manifold" }
    - { src: "qnas1.library.arizona.edu:/{{vm_hostname}}-manifold-logs", path: "/var/log/manifold" }
