---
# file: roles/_remove/tasks/main.yml

#- name: Issue shutdown command to service node.
#  command: "/sbin/shutdown -h now"
#  async: 0
#  poll: 0
#  ignore_errors: true
#  
#- name: Wait for shutdown.
#  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped

- name: Shutdown service node.
  delegate_to: localhost
  become: no
  vmware_guest:

    # vcenter connection parameters
    hostname: "{{ vmware_vcenter_host }}"
    username: "{{ vmware_vcenter_admin_username }}"
    password: "{{ vmware_vcenter_admin_password }}"
    validate_certs: "{{ vmware_vcenter_validate_certs }}"

    # vmware deployment parameters
    datacenter: "{{ vmware_guest_datacenter }}"
    cluster: "{{ vmware_guest_cluster }}"
    folder: "{{ vmware_guest_folder }}"
    name: "{{ vmware_guest_name }}"

    # vm state
    state: shutdownguest
    state_change_timeout: 300

- name: Remove service node.
  delegate_to: localhost
  become: no
  vmware_guest:

    # vcenter connection parameters
    hostname: "{{ vmware_vcenter_host }}"
    username: "{{ vmware_vcenter_admin_username }}"
    password: "{{ vmware_vcenter_admin_password }}"
    validate_certs: "{{ vmware_vcenter_validate_certs }}"

    # vmware deployment parameters
    datacenter: "{{ vmware_guest_datacenter }}"
    cluster: "{{ vmware_guest_cluster }}"
    folder: "{{ vmware_guest_folder }}"
    name: "{{ vmware_guest_name }}"

    # vm state
    state: absent
