---
# file: site_baseline.yml

#
# Ansible plays for applying the system roles to our baseline nodes,
# which then become the virtual machine templates used for our service
# nodes.
#
# Sample usage:
#
#     (To apply common configurations to baseline nodes:)
#     $ ansible-playbook site_baseline.yml --ask-vault-pass \
#                                          --inventory _support \
#                                          --limit baseline
#
# Note that for the _secured role, which implements CIS security
# benchmark configurations, you can use tags to limit which rules
# are applied -- see the associated task files under that role for
# more specifics.
#

- name: "Applying common configurations to baseline nodes:"
  hosts: aide
  remote_user: ansible-admin
  become: yes
  become_user: root
  gather_facts: true
  roles:
    - _secured
