---
# file: site_openaz.yml

#
# Service configurations for the Open Arizona service nodes; see
# comments in the "site.yml" file for further information.
#
# There are two separate plays in this playbook that use tags to
# invoke various roles on the service nodes:
#
# *   A "deploy" play that provisions the node, applies common
#     configurations, and then applies service-specific
#     configurations, resulting in a running service node;
#
# *   A "remove" play that first quiesces, then removes the
#     service node.
#
# Note that you can also use the "deploy" play to verify that
# running nodes are in the proper configured state.
#
# Sample usage:
#
#     (To create or verify service nodes:)
#     $ ansible-playbook site.yml --ask-vault-pass \
#                                 --inventory _testing \
#                                 --limit openaz \
#                                 --tags deploy
#
#     (To delete service nodes:)
#     $ ansible-playbook site.yml --ask-vault-pass \
#                                 --inventory _testing \
#                                 --limit openaz \
#                                 --tags remove
#
# In the above commands, you would specify "_staging" or "_production"
# for the inventory file to affect those service environments.
#

- name: Deploy Open Arizona service nodes
  hosts: openaz
  remote_user: ansible-admin
  become: yes
  become_user: root
  gather_facts: false
  roles:
    - _provision
    - _common
    - openaz
  tags:
    - deploy

- name: Remove Open Arizona service nodes
  hosts: openaz
  remote_user: ansible-admin
  become: yes
  become_user: root
  gather_facts: true
  roles:
    - openaz-quiesce
    - _remove
  tags:
    - remove
