---
# file: site_openaz.yml

#
# Ansible plays for provisioning, deploying, and removing Open Arizona
# service nodes.
#
# Sample usage:
#
#     (To provision Open Arizona service nodes:)
#     $ ansible-playbook site.yml --ask-vault-pass \
#                                 --inventory _testing \
#                                 --limit openaz \
#                                 --tags provision
#
#     (To deploy Open Arizona service configuration to provisioned nodes:)
#     $ ansible-playbook site.yml --ask-vault-pass \
#                                 --inventory _testing \
#                                 --limit openaz \
#                                 --tags deploy
#
#     (To remove Open Arizona service nodes:)
#     $ ansible-playbook site.yml --ask-vault-pass \
#                                 --inventory _testing \
#                                 --limit openaz \
#                                 --tags remove
#
# In the above commands, you could also specify "_staging" or
# "_production" for the inventory file to affect those service
# environments instead of "_testing".
#

- name: "Provisioning Open Arizona service nodes:"
  hosts: openaz
  remote_user: ansible-admin
  become: yes
  become_user: root
  gather_facts: false
  roles:
    - _provisioned
  tags:
    - provision

- name: "Deploying Open Arizona service nodes:"
  hosts: openaz
  remote_user: ansible-admin
  become: yes
  become_user: root
  gather_facts: true
  roles:
    - _identified
    - _equipped
    - _accessible
    - _synchronized
    - _secured
    - splunkf-installed
  tags:
    - deploy
    
- name: "Removing Open Arizona service nodes:"
  hosts: openaz
  remote_user: ansible-admin
  become: yes
  become_user: root
  gather_facts: false
  roles:
    - _removed
  tags:
    - remove
