---
# file: roles/_remove/tasks/main.yml

- name: Shutdown service node.
  delegate_to: localhost
  become: no
  vmware_guest:

    # vcenter connection parameters
    hostname: "{{ vmware_vcenter_host }}"
    username: "{{ vmware_vcenter_admin_username }}"
    password: "{{ vmware_vcenter_admin_password }}"
    validate_certs: "{{ vmware_vcenter_validate_certs }}"

    # vmware deployment parameters
    datacenter: "{{ vmware_guest_datacenter }}"
    cluster: "{{ vmware_guest_cluster }}"
    folder: "{{ vmware_guest_folder }}"
    name: "{{ vmware_guest_name }}"

    # vm state
    state: shutdownguest
    state_change_timeout: 300

- name: Remove service node.
  delegate_to: localhost
  become: no
  vmware_guest:

    # vcenter connection parameters
    hostname: "{{ vmware_vcenter_host }}"
    username: "{{ vmware_vcenter_admin_username }}"
    password: "{{ vmware_vcenter_admin_password }}"
    validate_certs: "{{ vmware_vcenter_validate_certs }}"

    # vmware deployment parameters
    datacenter: "{{ vmware_guest_datacenter }}"
    cluster: "{{ vmware_guest_cluster }}"
    folder: "{{ vmware_guest_folder }}"
    name: "{{ vmware_guest_name }}"

    # vm state
    state: absent
