---
# file: host_vars/openaz-tst.library.arizona.edu/vars.yml

# Environment parameters.

environment_name: Testing
environment_tag: tst
environment_baseline: ubuntu16-baseline-1
environment_url: http://openaz-tst.library.arizona.edu/

# Virtual machine network configuration.

vm_hostname: "{{ service_tag }}-{{ environment_tag }}"
vm_domain: library.arizona.edu
vm_fqdn: "{{ vm_hostname }}.{{ vm_domain }}"

vm_net_name: ens160
vm_net_type: static
vm_net_ipaddr: 150.135.174.13
vm_net_netmask: 255.255.255.0
vm_net_network: 150.135.174.0
vm_net_broadcast: 150.135.174.255
vm_net_gateway: 150.135.174.1
vm_net_mtu: 9000

# Virtual machine ssh keys.

vm_hostkey_dsa: "{{ vm_hostkey_dsa_v }}"
vm_hostkey_dsa_public: |
  ssh-dss AAAAB3NzaC1kc3MAAACBAKCZMOm3iASZWZnCYQ8RtRO8EZpNuIRBf6MsNsrr7HnjfqQpB3ZPjvCaayfZSU4+IPNXuMmyZxLCsGW52v0J0Ucz5w5/Mn2yZ/Bdyevsfc1ocsRSJqSqp8FmAdyzdMOeM6pDXekUMMG+N7I8GbqwIHnUUU8Mwo6Yjm6A9ahuq2n5AAAAFQC+Frh84mTmhH3rYDNNBTboFyGwFQAAAIA1S5RL2Qk9ok3Y13QcB2sRXI7rDYdf2cDsLNuLTCA00dhWSKhCaafYd21JeYCwcHkxpbJkEZI3vwnOvVEsPXjygwlcq0AvhQXfeJ7AB54m4xw5dgrt5n5LP2c4Fu1RVGsqoSimEliIowCqLIVct+B1z0zolRkGZfy2YZ0FczgrhgAAAIEAmY4GefFxWPj7fRhrJdPDZx233Up4IVXapv1iz1hsCTuwxLMsny2xrpNx/3Idjyh8z1MpPhPgrjcTD1jEsyTNX1zawIv30YGEB7WfmumDrbZvLiGZwtwTmkztU6uQU0Gae58JqjPi5IZXcfrzBvFoGiwFZCeGZuFkDlujGB8vOrU=
vm_hostkey_ecdsa: "{{ vm_hostkey_ecdsa_v }}"
vm_hostkey_ecdsa_public: |
  ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKrt4gNb3Yq/SL2yfrAKz7CcahyGMYUdBj3erZnxO9R6LeL44i/fcjSU3rcbnR9/KaBUI1P9S50VvlqrzHuVAz4=
vm_hostkey_ed25519: "{{ vm_hostkey_ed25519_v }}"
vm_hostkey_ed25519_public: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINM7QgwL2A6/YGVCi8jJOk6hdfTiEJfqnfOfnZZcWvuG
vm_hostkey_rsa: "{{ vm_hostkey_rsa_v }}"
vm_hostkey_rsa_public: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFeF9ZoSyvOTEfAbGTRGOSaqpsaOc8iALuy8OwenMOEWJd0Y5a2+6ARTDBwD84Me/8caiaenU1QwTgL9N7WAYFpAFqmGf3Sjy+3sfIcCzMndnMy/x4EClnPLNWcYPnGhaWHTi5d/1dUaISj6DJLWBUig5YiQGfsC1yM/ApPbCFqdNahg3xnv/pXY/gmSRUMB9HSv4pKAe0aBG6CkJ+1XqktMY2pV8OJOWwN9//GZk/lrnexXCaGMhfoTbjxmbywKQ7KkymXC+xZ3QVoocJKQHW9ZP3I8eEos22wPjuNLutsiAP9A7Xx+Rz84p8Ot5EOJ653dnPphqNS8r/AisxOh6N
