---
# file: roles/_secured/tasks/cis-1.1-filesystems-configured.yml

- name: "Check Updates:"
  block:

    - name: "On a CentOS system:"
      block:

        - name: (CentOS) Copy script to host
          copy:
            src: usr_local_bin_check-yum-updates.sh
            dest: /usr/local/bin/check-yum-updates.sh
            mode: 0755

        - name: (CentOS) Create /var/log/updates
          file:
            path: /var/log/updates
            state: directory

        - name: (CentOS) run update report
          cron:
            name: "update report"
            minute: "0"
            hour: "3"
            weekday: "*"
            job: "/usr/local/bin/check-yum-updates.sh > /dev/null 2>&1"

      when:
        - ansible_distribution == 'CentOS'

     
    - name: "On a Ubuntu system:"
      block:
      
        - name: (Ubuntu) Copy script to host
          copy:
            src: usr_local_bin_check-apt-updates.sh
            dest: /usr/local/bin/check-apt-updates.sh
            mode: 0755

        - name: (Ubuntu) Create /var/log/updates
          file:
            path: /var/log/updates
            state: directory

        - name: (Ubuntu) run update report
          cron:
            name: "update report"
            minute: "0"
            hour: "3"
            weekday: "*"
            job: "/usr/local/bin/check-apt-updates.sh > /dev/null 2>&1"

      when:
        - ansible_distribution == 'Ubuntu'

  tags:
    - check_updates