---
# file: roles/_synchronized/tasks/timezone-set.yml

- name: Set timezone.
  file:
    src: "/usr/share/zoneinfo/{{ vm_tzone }}"
    dest: "/etc/localtime"
    owner: root
    group: root
    state: link
