---
# file: roles/_common/tasks/main.yml

- name: Install common packages.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - emacs
    - nfs-common
    - open-vm-tools
    - sysstat
    - zsh
