---
# file: roles/_common/tasks/standard-packages.yml

- name: (CentOS) Install common packages.
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - emacs
    - nfs-utils
    - open-vm-tools
    - python
    - sysstat
    - zsh
  when:
    - ansible_distribution == "CentOS"

- name: (Ubuntu) Install common packages.
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - emacs
    - nfs-common
    - open-vm-tools
    - python
    - sysstat
    - zsh
  when:
    - ansible_distribution == "Ubuntu"
