---
- name: Manage accounts
  user: 
    name: "{{ item.username }}" 
    shell: "{{ item.shell }}" 
    state: "{{ item.user_state }}" 
  with_items: "{{ shell_users }}"

- name: Set authorized public keys
  authorized_key:
    user:  "{{ item.username }}"
    state: "{{ item.key_state }}"
    key: "{{ item.public_key }}"
  when: item.user_state == "present"
  with_items: "{{ shell_users }}"

- name: Manage /etc/sudoers file
  lineinfile:
    path: /etc/sudoers
    state: "{{ item.user_state }}"
    insertafter: EOF
    line: '{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
  when: 'item.use_sudo == True'
  with_items: "{{ shell_users }}"
