---
# file: group_vars/openaz/vars.yml

# Service parameters.

service_name: Open Arizona
service_tag: openaz
service_id: 5002

# Service group and user.

openaz_group_name: "{{ service_tag }}"
openaz_group_gid: "{{ service_id }}"

openaz_user_name: "{{ service_tag }}-admin"
openaz_user_uid: "{{ service_id }}"
openaz_user_comment: "{{ service_name }} Administrator"
openaz_user_shell: "/bin/bash"
openaz_user_home: "/home/{{ service_tag }}-admin"
openaz_user_group: "{{ openaz_group_name }}"
openaz_user_key_rsa: "{{ openaz_user_key_rsa_v }}"
openaz_user_key_rsa_public: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCflpi3VIRY01aFJNsBPYoiBKF4t6xCKpyjE4FQmf+e58NyJEBNj6b43oUX8FnuKtavmN1+lSdnouZGD67HYlGnRXE6ywJYtRwA5BBjtl92WnIy4RXv/K7r8meZmCBos5zgTSPhBYZKfguFbbFHuzGCwTI1y7bLjC06XbxPf7/juYdbCuSRJ0vpT5L43BIZw5G5qXhNcEU09evhmzZz9Xy8M25QShaHCHt0dcBwJo8FPwcVmHyYshxHzCWf4X+TGOmPDmHxSQuMFvVt/ckjAxNiNp6z5OOAxH52xlQetUNrVVHb9i6LkxcG/lKucuxZRnY48EnuhUUTB3A4V4V0GYDNtGhHHqgP4yajwiLPQrFVYQlK496ZXJlT9ZkT+TxkdS3PxSC1RjxMOZOZOGCIbjp2pWZgHo9JQVviV0HfVT84KZ5xBoof1DmYeFZ/v2ybF5yar+iz/tlI/aluqOvQmYsVSmiH5sH8k8QCN9LN5L6Bsrk4ZIQUeEYJoUoPTGkmCHSmAQ0hdQWti7ltocUDXet7vewCwop1CXjBc5w3BxuhqMiP1P3J+uriICpQqmB8H/knKmiU3khovWeejSA9XoPEsKKEAaqQdPr+Ends3jt6FFzxW6QXUh4K4UIucOx/XdsXDSLgyC6KmR3xigKtJOeyC4H9Tjy/dW1LLcoIIhrZTw== openaz-admin@ansible1

# Manifold installation and configuration parameters.

manifold_package_location: https://storage.googleapis.com/manifold-dist/ubuntu16
manifold_package_version: manifold_2.0.4-1_amd64.deb

manifold_admin_email: LBRY-OPS-LCU@email.arizona.edu
manifold_admin_password: "{{ manifold_admin_password_v }}"
manifold_admin_fname: Manifold
manifold_admin_lname: Superuser

manifold_email_smtp_server: smtpgate.email.arizona.edu
manifold_email_smtp_port: 25
manifold_email_from_address: "no-reply@{{ vm_fqdn }}"
manifold_email_from_name: UA Press
