---
# file: host_vars/openaz-stg.library.arizona.edu/vars.yml

# Environment parameters.

environment_name: Staging
environment_tag: stg
environment_baseline: ubuntu16-baseline-1
environment_url: http://openaz-stg.library.arizona.edu/

# Virtual machine network configuration.

vm_hostname: "{{ service_tag }}-{{ environment_tag }}"
vm_domain: library.arizona.edu
vm_fqdn: "{{ vm_hostname }}.{{ vm_domain }}"

vm_net_name: ens160
vm_net_type: static
vm_net_ipaddr: 150.135.174.14
vm_net_netmask: 255.255.255.0
vm_net_network: 150.135.174.0
vm_net_broadcast: 150.135.174.255
vm_net_gateway: 150.135.174.1
vm_net_mtu: 9000

# Virtual machine ssh keys.

vm_hostkey_dsa: "{{ vm_hostkey_dsa_v }}"
vm_hostkey_dsa_public: |
  ssh-dss AAAAB3NzaC1kc3MAAACBAI9F5cKU1G87Gn55ZnlcnBqj+E8znH8azo3OOmWxfz23E4BtqpFxxywLFhVMf2k2mN8LryKLr92MwM9vwubWNVbIwYdwBMbRjbA/44jBqiA3pIHfEX4Ev9zUy80yInPqANltejRwXoHtS+bC4sTYRqJeifzACApyXzRUkA3S23LlAAAAFQCJXCnchNjev3WaKqGhHonsiQKt+wAAAIBg7DswNktrEZINyzCEzghEprFRIcAWCiMlZ5or/ygE6sR7y0bfObU2UcUFiNaPUPTYg/wmlZ/+jMqWywDO6y8qdfJCkkrln/g0nqPJz91lzehXo0qQzEoWoGJ8V87iJamTP39g/pxS9w0oSK5+P80OWKIUDnlzGdaw2iJ+cPAEVQAAAIB581ZphTu6aL0pxgrC7tiiMaj3kVVUXO7jxt9yYpo+ImEDbozZaSO+96v7CduU3m/BBDIOPjndDoob+2IUD8Ge1Sp2Zygf7IwPXJLlSu1VTTb8ENY6Cyg4oD8VZ6vmBYFAYWaHM2PRIDA1aLwer9crv/f/XkShuD4bGJRy12JQ5Q==
vm_hostkey_ecdsa: "{{ vm_hostkey_ecdsa_v }}"
vm_hostkey_ecdsa_public: |
  ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEV/x4yee6rhq+TxFvrkKOI1e+sAx4Pv/Ud2pxYNIfC80+cT/wUn4xxLesnY/rjz8TIoioZ6bx3vfaaFVEOsWO8=
vm_hostkey_ed25519: "{{ vm_hostkey_ed25519_v }}"
vm_hostkey_ed25519_public: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN0inhCmkHJ22TfRfXA4KPQjfWZ7qmRSyv01ibdIsj8V
vm_hostkey_rsa: "{{ vm_hostkey_rsa_v }}"
vm_hostkey_rsa_public: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDvTLu04JcAMr+VcCWMFphqiMti1p9eRtdHiowrTxSDDaM1+ez8ODTGBs9kA+ZC75mqtnY9UkQhWpTHBV/a76w8YSOfiOUoDwOgP2uEKnoHU6M6MWDYHXxdUife+n6a80BJ/ie2tIICe4IrnD8ZsIryvuscaSqwIY9j7rVQMHl6RvnlaUYb0Vsu1/JhpEPqe7MYKoPE7AYcFkSPpkmFg3qfcbE4XQnrcbSUF23Tb5iETXtq7KmFv9DCidXZm/OijbBnK0wzjgFVeqdb5EiglXB7Zf9IyJhcJZcPfES4+yWiu5tq7+H0ilhP1iqd2hdwhXbMcnDQKvq6kmWUfHV/LQFl
