---
# file: roles/splunkf-installed/tasks/main.yml

- name: Check for previously installed splunk forwarder.
  stat:
    path: /opt/splunkforwarder
  register: splunkf_install_dir

- name: "Install splunk forwarder:"
  block:

    - name: "On a CentOS system:"
      block:

        - name: (CentOS) Install splunk forwarder via yum.
          yum:
            pkg: "{{ splunkf_package_location }}/{{ splunkf_package_rpm }}"
            state: present

      when:
        - ansible_distribution == 'CentOS'

    - name: "On an Ubuntu system:"
      block:

        - name: (Ubuntu) Install splunk forwarder via apt.
          apt:
            deb: "{{ splunkf_package_location }}/{{ splunkf_package_deb }}"
            state: present

      when:
        - ansible_distribution == 'Ubuntu'

    - name: Create splunk user seed file.
      template:
        src: opt_splunkforwarder_etc_system_local_user-seed.conf
        dest: /opt/splunkforwarder/etc/system/local/user-seed.conf

    - name: Change splunk permissions.
      file:
        path: /opt/splunkforwarder
        state: directory
        recurse: yes
        owner: splunk
        group: splunk

    - name: Accept splunk license.
      command: /opt/splunkforwarder/bin/splunk start --accept-license --no-prompt

    - name: Enable splunk start-on-boot.
      command: /opt/splunkforwarder/bin/splunk enable boot-start

    - name: Add splunk forwarding server.
      command: /opt/splunkforwarder/bin/splunk add forward-server {{ splunkf_server_target }}:9997 -auth {{ splunkf_admin_username }}:{{ splunkf_admin_password }}

    - name: Add splunk deployment server.
      command: /opt/splunkforwarder/bin/splunk set deploy-poll {{ splunkf_server_target }}:8089 -auth {{ splunkf_admin_username }}:{{ splunkf_admin_password }}

    - name: Restart splunk forwarder.
      command: /opt/splunkforwarder/bin/splunk restart

  when:
    - splunkf_install_dir.stat.exists == False

- name: Check splunk forwarder status.
  command: /opt/splunkforwarder/bin/splunk status
  ignore_errors: yes
  changed_when: "splunkf_status.stdout == 'splunkd is not running.'"
  register: splunkf_status

- name: Start splunk forwarder when stopped.
  command: /opt/splunkforwarder/bin/splunk start
  when:
    - "splunkf_status.stdout == 'splunkd is not running.'"
