---
# file: host_vars/openaz-prd.library.arizona.edu/vars.yml

# Environment parameters.

environment_name: Production
environment_tag: prd

manifold_package_location: https://storage.googleapis.com/manifold-dist/debian
manifold_package_version: manifold_1.0.1-1_amd64.deb
manifold_external_url: http://openaz-prd.library.arizona.edu

# Virtual machine network configuration.

vm_hostname: "{{ service_tag }}-{{ environment_tag }}"
vm_domain: library.arizona.edu
vm_fqdn: "{{ vm_hostname }}.{{ vm_domain }}"

vm_net_name: ens160
vm_net_type: static
vm_net_ipaddr: 150.135.174.15
vm_net_netmask: 255.255.255.0
vm_net_network: 150.135.174.0
vm_net_broadcast: 150.135.174.255
vm_net_gateway: 150.135.174.1
vm_net_mtu: 9000

# Virtual machine ssh keys.

vm_hostkey_ecdsa: "{{ vm_hostkey_ecdsa_v }}"
vm_hostkey_ecdsa_public: |
  ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFzXclGpq8u7/CBGu7KMAnG4tUwieFbJTzJv+HJf884mPkS23OiM0BmpuerI0tOdE+3Yi7lpTTTrvzpR+kATU70=
vm_hostkey_ed25519: "{{ vm_hostkey_ed25519_v }}"
vm_hostkey_ed25519_public: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHpngbQk2Fy7ekXhwcW/wd94KUV2M9DTjtMgAzQsiSLd
vm_hostkey_rsa: "{{ vm_hostkey_rsa_v }}"
vm_hostkey_rsa_public: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/FUTQtLbyeYOg8YfHDJW7lqERnnR1IawCeIW55/RljCvMrSvrkCAs+t8YlXlbWI7vrkiPMaHyiRquqWY+HHD5ED8jlA+esnQ2dl8r+tlKHmm0wxk5UCJxumYJI79vZuj85+FyBr0vgeAetg2fGFWVm838JBQJJhI/944X+yFnyUQVqMxXOUBVOG4PsrcTT9UGa+vnCvXtuNRUceG8cDu34O0D/VutObat7dzzZPYCyfpKOjj6q9v9iPlyYFr/fQ/gNxDXAK5jor2QB6IPYVGr1DpZph3CEvk5grL0T5FIXZh8wwjqvAzbvQTVeFTe+sDkin9DpPdR4OUR6JMAW1vL
