---
# file: roles/openaz/tasks/main.yml

- name: Create Open Arizona administrative group.
  group:
    name: "{{ openaz_group_name }}"
    gid: "{{ openaz_group_gid }}"
    state: present

- name: Create Open Arizona administrative user.
  user:
    name: "{{ openaz_user_name }}"
    uid: "{{ openaz_user_uid }}"
    comment: "{{ openaz_user_comment }}"
    shell: "{{ openaz_user_shell }}"
    home: "{{ openaz_user_home }}"
    group: "{{ openaz_user_group }}"
    state: present

- name: Create Open Arizona user ssh directory.
  file:
    path: "{{ openaz_user_home }}/.ssh"
    state: directory
    mode: 0755

- name: Install Open Arizona user ssh keys.
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { content: "{{ openaz_user_key_rsa }}", dest: "{{ openaz_user_home }}/.ssh/id_rsa", mode: "0400" }
    - { content: "{{ openaz_user_key_rsa_public }}", dest: "{{ openaz_user_home }}/.ssh/id_rsa.pub", mode: "0444" }

- name: Mount Manifold NAS shares.
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: nfs
    opts: "{{ qnas_nfs_opts }}"
    state: mounted
  loop:
    - { src: "qnas1.library.arizona.edu:/{{vm_hostname}}-manifold-var", path: "/var/opt/manifold" }
    - { src: "qnas1.library.arizona.edu:/{{vm_hostname}}-manifold-logs", path: "/var/log/manifold" }
    
- name: Install Manifold package.
  apt:
    deb: "{{ manifold_package_location }}/{{ manifold_package_version }}"
    state: present

- name: Install customized Manifold configuration file.
  template:
    src: etc_manifold_manifold.rb
    dest: /etc/manifold/manifold.rb
  notify:
    - reconfigure manifold
    - add manifold admin

- meta: flush_handlers

- name: Start Manifold services.
  systemd:
    name: manifold-runsvdir.service
    state: started
