---
# file: roles/openaz/tasks/main.yml

- name: Create Open Arizona administrative group.
  group:
    name: "{{ group_openaz_name }}"
    gid: "{{ group_openaz_gid }}"
    state: present

- name: Create Open Arizona administrative user.
  user:
    name: "{{ user_openaz_name }}"
    uid: "{{ user_openaz_uid }}"
    comment: "{{ user_openaz_comment }}"
    shell: "{{ user_openaz_shell }}"
    home: "{{ user_openaz_home }}"
    group: "{{ user_openaz_group }}"
    state: present

- name: Create Open Arizona user ssh directory.
  file:
    path: "{{ user_openaz_home }}/.ssh"
    state: directory
    mode: 0755

- name: Install Open Arizona user ssh keys.
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { content: "{{ user_openaz_key_rsa }}", dest: "{{ user_openaz_home }}/.ssh/id_rsa", mode: "0400" }
    - { content: "{{ user_openaz_key_rsa_public }}", dest: "{{ user_openaz_home }}/.ssh/id_rsa.pub", mode: "0444" }

- name: Install Manifold package.
  apt:
    deb: "{{ manifold_package_location }}/{{ manifold_package_version }}"
    state: present

- name: Install customized Manifold configuration file.
  template:
    src: etc_manifold_manifold.rb
    dest: /etc/manifold/manifold.rb
  notify:
    - reconfigure manifold
    - add manifold admin
